name: booster
description: "A collection of useful widgets, extensions and utilities to boost Flutter app development."
version: 0.0.1
homepage: https://github.com/codingmitra/booster
repository: https://github.com/codingmitra/booster
issue_tracker: https://github.com/codingmitra/booster/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

funding:
  - https://buymeacoffee.com/hirokbanik

topics:
  - flutter
  - widgets
  - extensions
  - utilities